CREATE TABLE sms_bridge_config (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1
  INCREMENT BY 1 )                                                        NOT NULL,
  tenant_id               VARCHAR(32)                                     NOT NULL,
  api_key                 VARCHAR(32)                                     NOT NULL,
  endpoint                VARCHAR(256)                                    NOT NULL,
  mifos_token             VARCHAR(256)                                    NOT NULL,
  sms_provider            VARCHAR(32)                                     NOT NULL,
  sms_provider_account_id VARCHAR(256)                                    NOT NULL,
  sms_provider_token      VARCHAR(32)                                     NOT NULL,
  phone_no                VARCHAR(255)                                    NOT NULL,
  created_on              TIMESTAMP                                       NOT NULL,
  last_modified_on        TIMESTAMP                                       NOT NULL,
  UNIQUE (tenant_id)
);

CREATE TABLE event_sourcing (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY (
  START WITH 1
  INCREMENT BY 1 )                                                               NOT NULL,
  tenant_id        VARCHAR(32)                                                   NOT NULL,
  entity           VARCHAR(32)                                                   NOT NULL,
  action           VARCHAR(32)                                                   NOT NULL,
  payload          VARCHAR(4096)                                                 NOT NULL,
  processed        BOOLEAN DEFAULT FALSE                                         NOT NULL,
  error_message    VARCHAR(256),
  created_on       TIMESTAMP                                                     NOT NULL,
  last_modified_on TIMESTAMP                                                     NOT NULL
);